### ISSUE TITLE
run tests non-interactively

### ISSUE THREAD

**Issue by luismbo** [lmj/1am#3]
It'd be nice to be able to run tests non-interactively, i.e. printing some failure info and skipping to the next test. Is this something you'd consider accepting as a PR?

**Comment by phoe** [comment]
@luismbo it might be a little bit too much for 1am that IIUC strives to be minimalistic.

Take a look at https://gitlab.common-lisp.net/dkochmanski/2am which is one hour later and has the functionality you request.

**Comment by luismbo** [comment]
@phoe cool, thanks for the pointer.

**Comment by luismbo** [comment]
I suppose it'd be hard to implement this and keep the _Checks may occur inside threads_ feature. 🤔

**Comment by phoe** [comment]
I guess so, yes. Each individual thread may now enter the debugger on its own, which allows you to interactively inspect the state of the stack immediately when the debugger is entered.

**Comment by luismbo** [comment]
Having thought about this a bit more, I'm fairly convinced that adding this feature would ruin 1am's minimalism. Closing. :-)
